### ISSUE TITLE
500 on adding person to team

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1172]
### Expected Behavior

for someone to be added to the team

### Actual Behavior

HTTP 500

### Reproduction Steps

```markdown
1. add their **uuid** into the field, sid64 apparenly doesn't work
2. press the add button
3.
```

### Browsers

Firefox 98 (MacOS M1)

### Example URL

https://staging.gmodstore.com/dashboard/teams/DENt4n2TQiOTahk9djJxfg/users

### GmodStore Version

v11.0.0-beta.7

### Event ID

a68438fba212480ca16a30ed952f44ee

**Comment by TheodoorP** [comment]
Fixed in beta-8

**Comment by FelixKLG** [comment]
@TheodoorP Afraid I am still getting a 500
Sentry: 02b5407875764a73b39324fc01006ef8

**Comment by TheodoorP** [comment]
Fixed in beta-10
