### ISSUE TITLE
Mini search bar producing strangely weighted responses

### ISSUE THREAD

**Issue by joshua-bouv** [everyday-as/gmodstore-issues#933]
## Expected Behavior
In my opinion, it should display scripts with the word/s in the title first, before displaying scripts with it in the description.

## Actual Behavior
If you search "stock", a script with "this addon is stocked with features" shows up first - not because it's anything related to stocks or stocking products in a shelf etc. This is because, as mentioned, it includes this addon is "stocked with features" in the description.

![alt text](https://cdn.discordapp.com/attachments/280079217021026314/761940878888665088/unknown.png "Logo Title Text 1")
![alt text](https://cdn.discordapp.com/attachments/280079217021026314/761942172491841556/unknown.png "Logo Title Text 1")

## Steps to Reproduce the Problem

  1. Search for a script  on the mini search bar

## Specifications

  - GmodStore version (see footer): 7.1.33
  - Browser: Chrome (not relevant)

**Comment by Marcuzz** [comment]
Is this still an occurring issue? We fixed something like this a little while ago I believe

**Comment by joshua-bouv** [comment]
> Is this still an occurring issue? We fixed something like this a little while ago I believe

Still the same results. Potentially an improvement could be for when it's finding matching words in the description, these are weighted less than finding the word in the title as it seems prone to being over ambitious with finding the word in the description (like with my example, when searching for stock the top result would be a script with the word "stocked with features" in the description) as currently it seems items are ordered on the basis of what has the most sales only.

An extra bug is that if you type for something, clear what you typed and type something else, it retains all the previous results making it a long list of all kinds of scripts in the search bar.

**Comment by joshua-bouv** [comment]
It would seem that the issue has now been resolved, being that it is showing considerably less irrelevant results and putting addons with the search query in the title first 👍😃
